table 'Country stats'
	lineageTag: 9bb57142-b21e-4646-8523-65bb68bc0c81

	column origin_country
		dataType: string
		lineageTag: 76b6f54d-b272-4db0-a5a6-2b64c80d60ad
		summarizeBy: none
		sourceColumn: origin_country

		annotation SummarizationSetBy = Automatic

	column flight_count
		dataType: int64
		formatString: 0
		lineageTag: 3ba4bf0f-279c-4955-85a2-dcf55be09167
		summarizeBy: none
		sourceColumn: flight_count

		annotation SummarizationSetBy = Automatic

	column avg_speed_ms
		dataType: double
		lineageTag: 9a676e8b-6a7f-47a5-a345-684d3149fcaa
		summarizeBy: none
		sourceColumn: avg_speed_ms

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_altitude_m
		dataType: double
		lineageTag: d43deca6-fd8b-426e-9647-f1b0e85f51ae
		summarizeBy: none
		sourceColumn: avg_altitude_m

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Country stats' = m
		mode: import
		source =
				let
				    Source = AzureStorage.DataLake("https://aviationdatalakegary.dfs.core.windows.net/"),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Folder Path] = "https://aviationdatalakegary.dfs.core.windows.net/gold/country_stats/") and ([Name] = "part-00000-c60034c6-0c69-4db3-8ceb-82d37b2b8ce1-c000.snappy.parquet")),
				    #"Filtered Hidden Files1" = Table.SelectRows(#"Filtered Rows", each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (3)", each #"Transform File (3)"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File (3)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (3)", Table.ColumnNames(#"Transform File (3)"(#"Sample File (3)"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"origin_country", type text}, {"flight_count", Int64.Type}, {"avg_speed_ms", type number}, {"avg_altitude_m", type number}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Source.Name"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

